#ifndef __LOGIN_CACHE_H__
#define __LOGIN_CACHE_H__
#include <string.h>
#include <stdlib.h>
#include "configfilereader.h"
#include "util.h"
#include "acl_cpp/lib_acl.hpp"
#include "acl_cpp/redis/redis_hash.hpp"
#include "acl_cpp/redis/redis_key.hpp"



//#define REDIS_FIELDS_COUNT 15

using namespace std;


typedef enum _user_state
{
	USER_OFFLINE = 0,
	USER_ONLINE
} user_state;

typedef enum _cache_fields
{
	IP_FIELD = 0,
	PORT_FIELD,
	STATUS_FIELD,
	LOGINTOKEN_FIELD,
	DEVICETOKEN_FIELD,
	RELOGIN_FIELD,
	LOGINTIME_FIELD,
	RELOGINTIME_FIELD,
	CALLSTATUS_FIELD,
	SESSION_ID_FIELD,
	PUSHTYPE_FIELD,
	PUSHTOKEN_FIELD,
	ISPUSH_FIELD,
	REDIS_FIELDS_COUNT		//!!!这个用来计数，一定要放在最后
} cache_fields;


typedef struct _RedisPara
{
	int32_t nConnTimeout;
	int32_t nRwTimeout;
	int32_t nRetryInterval;
	int32_t nRetrySleep;
	int32_t nRetryLimit;
	int32_t nPoolSize;
	int32_t nKeyExpireTime;
	acl::string sRedisAddrs;
	acl::string sPassword;
} RedisPara_t;


typedef struct _UserCache
{
	acl::string sUserId; 		// redis cache key. (cm)_userId
	uint8_t bStatus;			// user on/off line status, 0: offline; 1: online; 2:pending
	uint8_t bRelogin;			// 0: new login ; 1: relogin;
	uint16_t nIPPort;			// current CM server Port 
	acl::string sIPAddr;		// current CM server IP address
	acl::string sLoginToken;    // generated by user center to validate user . 
	acl::string sDeviceToken;	// device token string.
	acl::string sReloginTime;	// Refresh relogin timestamp .
	acl::string sLoginTime;		// The firt timestamp that user login . 
	acl::string sSessionId;		// 唯一标识
	uint16_t nPushType;			// 推送类型
	acl::string sPushToken;		// 推送token
} UserCache_t; 

typedef struct _DeviceCache
{
	acl::string sDeviceToken;	// device token string. 
	acl::string sSubscriptId;	// subscript string. 
} DeviceCache_t;

class CLoginCache
{
public:
	CLoginCache(CConfigFileReader* pConfigReader);
	~CLoginCache();
	bool Initialize(void);
	bool GetUserStatus(acl::string sUserId,uint8_t &bStatus);
	bool SetUserStatus(acl::string sUserId,int8_t bStatus);
	bool SetUserExpireTime(acl::string sUserId);
	bool RemoveUserExpireTime(acl::string sUserId);
	bool UpdateUserRec(UserCache_t &rec);
	bool GetUserRecord(acl::string sUserId,UserCache_t &rec);
	bool GetDeviceRecord(acl::string sDeviceToken,DeviceCache_t &rec);
	bool InsertUserRec(UserCache_t &rec);
	bool InsertDeviceRec(DeviceCache_t &rec);
	bool DelUserRec(acl::string sUserId);
	bool DelDeviceRec(acl::string sDeviceToken);

	bool SetUserPushState(acl::string sUserId, int push);
protected:
	bool SetRedisPara(void);	
private:
	CConfigFileReader* m_pConfigReader;
	RedisPara_t m_redisPara;
	acl::redis_client_cluster m_cluster;
	acl::redis_hash m_hashRedis;
	acl::redis m_redis;
};

#endif  //__LOGIN_CACHE_H__

