#!/bin/sh

ln -s libmongoc-1.0.so.0.0.0 libmongoc-1.0.so.0
ln -s libmongoc-1.0.so.0 libmongoc-1.0.so
ln -s libbson-1.0.so.0.0.0 libbson-1.0.so.0
ln -s libbson-1.0.so.0 libbson-1.0.so
ln -s libmysqlclient.so.18.0.0 libmysqlclient.so.18
ln -s libmysqlclient.so.18 libmysqlclient.so
ln -s libmysqlclient.so libmysqlclient_r.so
#ln -s libprotobuf-lite.so.10.0.0 libprotobuf-lite.so.10
#ln -s libprotobuf-lite.so.10 libprotobuf-lite.so
ln -s libprotobuf-lite.so.17.0.0  libprotobuf-lite.so.17
ln -s libprotobuf-lite.so.17.0.0 libprotobuf-lite.so
ln -s libprotobuf.so.17.0.0  libprotobuf.so.17
ln -s libprotobuf.so.17.0.0 libprotobuf.so
ln -s liblog4cxx.so.10.0.0 liblog4cxx.so.10
ln -s liblog4cxx.so.10 liblog4cxx.so
ln -s libmongocxx.so._noabi libmongocxx.so
ln -s libbsoncxx.so._noabi libbsoncxx.so
ln -s libzookeeper_mt.so.2.0.0 libzookeeper_mt.so.2
ln -s libzookeeper_mt.so.2 libzookeeper_mt.so
ln -s libnghttp2.so.14 libnghttp2.so
ln -s libgpr.so.6.0.0 libgpr.so
ln -s libgpr.so libgpr.so.6
ln -s libgrpc.so.6.0.0 libgrpc.so
ln -s libgrpc.so libgrpc.so.6
ln -s libgrpc++.so.1.16.1 libgrpc++.so
ln -s libgrpc++.so libgrpc++.so.1
ln -s libuuid.so.1.3.0 libuuid.so.1 
ln -s libuuid.so.1 libuuid.so
