// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: im.radio.proto

#include "im.radio.pb.h"
#include "im.radio.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace radionotify {

static const char* RadioNotifyService_method_names[] = {
  "/radionotify.RadioNotifyService/OnRadioMsgNotify",
};

std::unique_ptr< RadioNotifyService::Stub> RadioNotifyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RadioNotifyService::Stub> stub(new RadioNotifyService::Stub(channel));
  return stub;
}

RadioNotifyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_OnRadioMsgNotify_(RadioNotifyService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RadioNotifyService::Stub::OnRadioMsgNotify(::grpc::ClientContext* context, const ::radionotify::RadioMsgNotify& request, ::radionotify::RadioMsgNotifyACK* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_OnRadioMsgNotify_, context, request, response);
}

void RadioNotifyService::Stub::experimental_async::OnRadioMsgNotify(::grpc::ClientContext* context, const ::radionotify::RadioMsgNotify* request, ::radionotify::RadioMsgNotifyACK* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_OnRadioMsgNotify_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::radionotify::RadioMsgNotifyACK>* RadioNotifyService::Stub::AsyncOnRadioMsgNotifyRaw(::grpc::ClientContext* context, const ::radionotify::RadioMsgNotify& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::radionotify::RadioMsgNotifyACK>::Create(channel_.get(), cq, rpcmethod_OnRadioMsgNotify_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::radionotify::RadioMsgNotifyACK>* RadioNotifyService::Stub::PrepareAsyncOnRadioMsgNotifyRaw(::grpc::ClientContext* context, const ::radionotify::RadioMsgNotify& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::radionotify::RadioMsgNotifyACK>::Create(channel_.get(), cq, rpcmethod_OnRadioMsgNotify_, context, request, false);
}

RadioNotifyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RadioNotifyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RadioNotifyService::Service, ::radionotify::RadioMsgNotify, ::radionotify::RadioMsgNotifyACK>(
          std::mem_fn(&RadioNotifyService::Service::OnRadioMsgNotify), this)));
}

RadioNotifyService::Service::~Service() {
}

::grpc::Status RadioNotifyService::Service::OnRadioMsgNotify(::grpc::ServerContext* context, const ::radionotify::RadioMsgNotify* request, ::radionotify::RadioMsgNotifyACK* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace radionotify

